kind: ServiceAccount
apiVersion: v1
metadata:
  name: start-stop-prod
  namespace: sentiment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-deployment
  namespace: sentiment
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch", "scale"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-deployment
  namespace: sentiment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-deployment
subjects:
  - kind: ServiceAccount
    name: start-stop-prod
    namespace: sentiment
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-prod-deployment
  namespace: sentiment
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '15 8 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: start-stop-prod
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - bash
            - -c
            - |
              kubectl -n sentiment patch deployment sentiment-backend --patch '{"spec":{"replicas":1}}'
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-prod-deployment
  namespace: sentiment
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '45 15 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: start-stop-prod
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - bash
            - -c
            - |
              kubectl -n sentiment patch deployment sentiment-backend --patch '{"spec":{"replicas":0}}'
